env:
  global:
    - secure: "Oh5QdSFJ0hnerIXJgtZlU+afn9yHVux2z19apFBmxioQ76zpIra/uxE0eDq4oW56wT5W/VAo2hncUdEr3d68PYD/Voyh6sLuOdIrF08j2FLPf+3h3oHhUGzsKMpNXDX0IIvfE8HNcZfAqcNS+vhbgD4drRCWvc7Z/SzOSGK+l9ZK+ay071SRlZcnrP8UHYv03Z8JJaEEpb0HGZNBVFUQPMEBD8ET8zv003qMMImKI6K8PBFa2A6Ip+N4wRDHDWdGo6XkHDBKjZijNjDQgGCgcctNGlyzwIn9eNUdXcm+ScPacHFMGlD0JdoMkkPkDr3WlaPjwBUOablEOkzSj/UyAcll8aIoLecRrE2wFQV+tw+/DZIT5SgzTAzZg5xwm2yVOUB8F5efRttAU4++EKlyN5arfCFpTuKlqGMeQVb4BLDZiqyVxMm0cw94/XJgBgSHE9aFkxhtGgsaHeRJRDhoEPyfhYoQX5U14P+2zolfrKWO4NTINaaJdxsqOIQ9ooyVF6JoiUyK2RCu6FSQCGSPMeuNsDU/7We5NQLI6k1xsGZ5Mi5nUcCsTniraTn3A78uWoDyXPqWqc/+vAdKXdy81b96sDUt7jNuQ4pHfn+z2QE8toDtofE+0WNN1NoV6TWf2jSnrepew4bwbAIV0lDlOb9nDPt0rlF5JcHy3TVfYE0="
    - secure: "fubpyaWISSYKAfQvjcW7rbJpL5VNjUzvkY9bD29w4NhIJIHovXBQ8EeRmlsxLqXIT+KuzWp8DT1yKYbXbtpH8eD+I+Mg8hZDEa/Nza29pENLgsG+cJo6KhLry4ZdzX3elvpi7kNIuxIr0jcc2rEGkBhqqH7N5vgCEA/ZrEzOWQLtg1t2c9VdTa6OWfomZjJYK8kddjEYXiSeztKAQ6BBlspnGmX+no1iz2ZZADsSvjWV7KEMs6vBy16stL/rPkADzrt3Lc9pCjfoDTAots3s8fORGueLSb8VSgRdv/KjZAvOc3o0VPMRs3ed/ALyPrgSxwxSvUF4NKDxlKM9AujchvFyJcaolYHNqHIlhpR/X5Vzph51pyoPtLpG5lBw8oUSqrwjqyYHWgIF0Ay6c6tQTyD8IU2hll0Ib4yPjp6pAhThiuXwwRrC5Sunfeo59BfauefyYQIuv1R9OFKC4/BBL2/KOFtgqZAFmHi+5g0ookBOhTZh0HCPzaDFe8KBnnhd9YWwuIokRIdh0Vks8CYDmpnSeFyqNgnJCPRXHMPSxm0bFGxhwSRUPi/JdxtZqf7o5PlLEddqlZuStBJZzVEVva081I/8/9ec6kY72u+qAUtmxQp/fNTCcP+n16jBo2tNbJcaksJnBCv8u8UKhFs08ShSlmabtz+uGtirvmIyl1A="

language: java

script:
- mvn -B clean package docker:build

cache:
  directories:
  - $HOME/.m2

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push wjung/imap-pdf-ocr:latest
- docker push wjung/imap-pdf-ocr:`mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`

branches:
  only:
  - master
